# Generated by Django 3.1.7 on 2021-11-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=32)),
                ('value', models.DecimalField(decimal_places=16, max_digits=32)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
