# Generated by Django 3.1.7 on 2021-11-28 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.controller')),
            ],
        ),
        migrations.AddField(
            model_name='dataentry',
            name='controller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.controller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataentry',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.device'),
            preserve_default=False,
        ),
    ]
