# Generated by Django 3.1.7 on 2021-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211127_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='name',
            field=models.CharField(auto_created=True, max_length=128, unique=True),
        ),
    ]
