# Generated by Django 3.1.7 on 2021-11-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211128_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='controller',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
