# Generated by Django 3.1.7 on 2021-11-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211128_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.controller'),
        ),
    ]
