# Generated by Django 3.1.7 on 2021-11-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211128_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.controller'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.device'),
        ),
    ]
