# Generated by Django 3.1.7 on 2022-01-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211128_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='target',
            field=models.FloatField(default=10.0, max_length=128),
            preserve_default=False,
        ),
    ]
